version: '3.8'

services:
  app:
    image: 'spring-app:latest'
    build:
      context: .
    container_name: spring
    depends_on:
      - db
      - elasticsearch
    develop:
      watch:
        - action: rebuild
          path: ./src
        - action: rebuild
          path: pom.xml
    volumes:
      - ./src:/app/src
      - ./target:/app/target
      - ./logs:/app/logs
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/curcus
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Ngocquynguyen1
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
    ports:
      - "8080:8080"
    networks:
      - app_network

  db:
    image: 'postgres:17.2-alpine3.21'
    container_name: pgsql
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Ngocquynguyen1
      - POSTGRES_DB=curcus
    networks:
      - app_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - app_network

volumes:
  elasticsearch-data:
  postgres-data:

networks:
  app_network:
    driver: bridge